import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import { GeistSans } from 'geist/font/sans';
import { Toaster } from "@/components/ui/toaster"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={GeistSans.className + " h-full"}>

        <Providers>
          {children}
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
